### ISSUE TITLE
Blank area where the DateViewer information typically displays

### ISSUE THREAD

**Issue by Valthari-n** [hammy1/BDStuff#10]
![Discord_LJJr39RwsG](https://user-images.githubusercontent.com/63422181/88448878-c301f600-ce07-11ea-903f-f1a284b4d54e.png)
I had messed with the config file a while ago, so I now decided to delete it, but that hasn't remedied anything.

**Comment by hammy1** [comment]
Should be fixed now thanks to Arashiryuu.
